### ISSUE TITLE
קבצי JSON

### ISSUE THREAD

**Issue by eilon40** [Y-Moshe/fxp-generator#1]
https://pastebin.com/aekC0Rda
https://pastebin.com/sdrtX1w2

מוזמן להיעזר בהם (:

**Comment by Y-Moshe** [comment]
thanks, ill make use of it, the first one looks relevant indeed  👍

**Comment by Y-Moshe** [comment]
Hi @eilon40, can you look at this file: https://github.com/Y-Moshe/fxp-generator/blob/master/src/forums-data.json
is there a way to add all of "קישור לאשכול משקיען השבוע לכל פורום"?
and btw, what's ur nickname at FxP?(just to know u)

**Comment by eilon40** [comment]
> Hi @eilon40, can you look at this file: https://github.com/Y-Moshe/fxp-generator/blob/master/src/forums-data.json
> is there a way to add all of "קישור לאשכול משקיען השבוע לכל פורום"?
> and btw, what's ur nickname at FxP?(just to know u)
השתמש בקוד הזה
https://pastebin.com/fP5YPbr2
על מנת לאחד בין 2 הקבצים

ליצירת קשר איתי מוזמן ליצור קשר אם המפקח שלך
ולבקש את הפרטים שלי

**Comment by Y-Moshe** [comment]
Thanks, that helped :)
