### ISSUE TITLE
בעיית לוגואים בקטגורית לימודים והשכלה

### ISSUE THREAD

**Issue by gilkzxc** [Y-Moshe/fxp-generator#12]
לא מעט פורומים אצלינו במחולל עם לינקים של הלוגואים שבורים/לא תקינים.
אני אעבור ואתקן בהזדמנות (כנראה שבוע הבא, עם בקשת pull )

**Comment by Y-Moshe** [comment]
any news?

**Comment by DanielNordman** [comment]
טיפלתי בהכרזות שלו.
