### ISSUE TITLE
שינוי לוגואים בקטגוריית אנדרואיד

### ISSUE THREAD

**Issue by moyalmusic** [Y-Moshe/fxp-generator#17]
היי מה שלומך? אני ליאור מפקח קטגוריית אנדרואיד ([KreweIla](https://www.fxp.co.il/member.php?u=652252))
ישנן כמה תקלות בהכרזות ברחבי קטגוריית אנדרואיד שאשמח אם תסדר אותם בזמנך הפנוי כמובן :)
אנדרואיד כללי - https://i.imagesup.co/images2/b7d5534d4410524abc992d2c864b70ab10d90001.png
אפליקציות אנדרואיד - https://i.imagesup.co/images2/5cd185087337ddcb1df629a4ae408e083c8a20df.png
מכשירי סמסונג - https://i.imagesup.co/images2/1fd48773e039815da1e81554492fa0f8a710a1c2.png
מכשירי וואן פלוס - https://images.weserv.nl/?url=www.up2me.co.il%2Fimgs%2F27952358.png
מכשירי הוואי ושיאומי - https://i.imagesup.co/images2/ec4779ba133c6106b10239a8bdbb9a749ddafbb1.png
רומים ותוכנות - https://i.imagesup.co/images2/65c22d1497bf42ab9add05efd097bcffd3320d36.png
טאבלטים אנדרואיד - https://i.imagesup.co/images2/a50d91dbbd1e514bb47652f3087612af41b9ac03.png

תודה רבה מראש והמשך שבוע מקסים!

**Comment by Y-Moshe** [comment]
בוצע, לפעם הבאה אם אפשר לרשום את שם הפורום כפי שהוא בדיוק, לדוגמא הפורום `מכשירי Samsung` ולא "מכשירי סמסונג", ככה אוכל לחפש ולעדכן מהר יותר.
