### ISSUE TITLE
מחולל אתגרים

### ISSUE THREAD

**Issue by ModerniMan** [Y-Moshe/fxp-generator#22]
להוסיף מחולל אתגרם רגילים 
מחולק לחוקים וכד

**Comment by Y-Moshe** [comment]
תוכל לפרט יותר בבקשה?

**Comment by koko-game** [comment]
לדוגמא אני רוצה להעביר אתגר סטנדרטי איוונט וכד שיהיה לי אופציה לבחור לוגואים (חוקים, זמנים וכד) מפרידים וכד ולמלא את כל מה שארצה ויצא לי קוג

**Comment by Y-Moshe** [comment]
זה נשמע לי יותר מידי עבודה, ובהתייחס לזמן שכרגע זה לא אפשרי אבל אולי בעתיד.

בעיקרון ה"כלי עזר" נועד לעזור באופן כללי לאתר, זאת אומרת משהו שהוא משותף לכולם, לדוגמא אתגר השבוע זה משותף לכולם לכן יש אותו, משהו שהוא ספציפי לפורום מסויים אני לא עושה.
עכשיו, אני לא בטוח אם הבנתי נכון, האם המחולל האתגרים הוא משהו ספציפי לפורום?

**Comment by ModerniMan** [comment]
כללי לכולם לווא דווקא לפי פורום

**Comment by DanielNordman** [comment]
@ModerniMan לא שולל את ההצעה, אבל אם כל האתגרים יצאו מאותו תוסף, עיצוב האשכול יראה רובוטי ויחזור על עצמו.
זה למה עדיף ללמוד את המדריך המתקדם לטבלאות של איתמר https://www.fxp.co.il/showthread.php?t=16663328
ולעשות עיצובים משלך לאתגרים, ללמוד קצת איך לעצב אשכול.
הנה לדוגמה עיצוב לאשכול:
https://www.fxp.co.il/showthread.php?t=21141929

**Comment by ModerniMan** [comment]
טבלאות אני יודע
