### ISSUE TITLE
אתגרים שבועיים

### ISSUE THREAD

**Issue by ModerniMan** [Y-Moshe/fxp-generator#23]
אפשרות לעלות באופן ידני לוגואים של אתגרים שבועיים

**Comment by Y-Moshe** [comment]
תוכל לפרט יותר בבקשה.
איזה לוגואים?

**Comment by koko-game** [comment]
אם יש לי לוגו משלי למשקיען השבוע ואשכול השבוע שאוכל

**Comment by DanielNordman** [comment]
> > אם יש לי לוגו משלי למשקיען השבוע ואשכול השבוע שאוכל
> 
> בעיקרון זה נשמע אפשרי. להעלות תמונה ישירות מהאתר שלי לא אפשרי, אך לחלופין ניתן להעלות את התמונה באתר FXP ולתת את הקישור הישיר לתמונה.
> 
> אשב על זה מתישהו, תודה.

אם בסוף מי שירצה להשתמש בלוגואים משלו, יאלץ להחליף בכל פעם קישור בתבנית.
ממילא ולא הייתה נגיד אפשרות לכך, היה ניתן להחליף לוגו באשכול עצמו.
אותה פעולה אותה תוצאה, ואתה פשוט תעשה עוד קודינג לחינם.
