### ISSUE TITLE
אופנה והלבשה

### ISSUE THREAD

**Issue by IdanSG** [Y-Moshe/fxp-generator#25]
שלום :)
פורום אופנה והלבשה וטיפוח אישי התאחדו, לכן צריך לשנות את שם הפורום ל-אופנה וטיפוח אישי. גם בהכרזה וגם בהודעה.
תודה

**Comment by Y-Moshe** [comment]
היי עידן, 

צריך לתת את השם המדוייק של הפורמים כפי שהיו לפני כן, רק כדי להיות בטוח, האם אלו הן:

- אופנה והלבשה
- עיצוב, טיפוח ואופנה

בנוסף אני צריך שתיתן לי את ה: 

- שם הפורום אליו לשנות (שנתת).
- קישור ישיר לתמונת הפורום.
- קישור ישיר לאשכול של אתגר השבוע / משקיען השבוע של הפורום.

מחכה לתגובה.

> שלום :) פורום אופנה והלבשה וטיפוח אישי התאחדו, לכן צריך לשנות את שם הפורום ל-אופנה וטיפוח אישי. גם בהכרזה וגם בהודעה. תודה

**Comment by DanielNordman** [comment]
אהלן, לפי ההפרסות זה נראה שהשמות של הפורומים באורגינל היו:
- אופנה והלבשה
- טיפוח אישי ושיער

אשלים את מה שביקשת בשמו:
- שם הפורום אליו משנים: אופנה וטיפוח אישי
- קישור ישיר לתמונת הפורום חסוי
- הקישור הישיר: https://www.fxp.co.il/showthread.php?t=8212326

**Comment by Y-Moshe** [comment]
> 

עודכן, אלו הפורמים שנמחקו:

- אופנה והלבשה
- טיפוח אישי ושיער

עדכן שבסדר.

**Comment by Y-Moshe** [comment]
@DanielNordman האם זה עודכן בסדר והכל תקין?

**Comment by DanielNordman** [comment]
@Y-Moshe Guess so, perhaps @IdanSG shall test it today for the Weekly Task.

**Comment by IdanSG** [comment]
הכל תקין. תודה רבה :)
