### ISSUE TITLE
לימודים והשכלה

### ISSUE THREAD

**Issue by Webbfxp** [Y-Moshe/fxp-generator#26]
היי. ראשית, תודה רבה על התוסף של המחולל לאתגרים השבועיים. שאלתי היא, האם ניתן להוסיף את העיצוב הללו [https://www.fxp.co.il/showthread.php...#post217704237](https://www.fxp.co.il/showthread.php?t=19921760&page=2&p=217704237#post217704237) כך שיהיו תקפים לפורומים בקטגוריית השכלה גבוהה בלבד? לצורך העניין לעשות מחולל נפרד ללימודים והשכלה עם אותם עיצובים?

**Comment by Y-Moshe** [comment]
היי,

קודם כל, אני לא יכול להיכנס ללינק ששלחת עקב הרשאות אז אני לא יכול לראות :/.

אבל בעקרון כמו שאמרתי לפני כן למישהו שביקש להוסיף את המחולל, שזה בסדר, אבל מה שאתה מבקש לפחות לפי מה שכתוב נראה שזה ספציפית לפורום...

_"בעיקרון ה"כלי עזר" נועד לעזור באופן כללי לאתר, זאת אומרת משהו שהוא משותף לכולם, לדוגמא אתגר השבוע זה משותף לכולם לכן יש אותו, משהו שהוא ספציפי לפורום מסויים אני לא עושה"_

ואל תודה לי עדיין כי עוד לא עשיתי אל מחולל האתגרים.. :P.

**Comment by Webbfxp** [comment]
הכוונה שלי היא שיש קטגוריות מסויימות שמעוניינות להשתמש בעיצובים של משקיען השבוע ואשכול השבוע משלהן ואם אפשר להוסיף למחולל את התמונות הללו זה יהיה מצוין. שיהיה תקף לכל הקטגוריה.

**Comment by DanielNordman** [comment]
משה, זה השינוי בסטייל של משקיען ואשכול השבוע שהוצאתי בData.tsx.
זה לכלל קטג' לימודים והשכלה, לא רק פורום אחד. זה כמו שיש שם משקיען עם כתר ומשקיען עם כובע קש.
