### ISSUE TITLE
עדכון שמות פורומים ולוגואים לימודים והשכלה

### ISSUE THREAD

**Issue by Webbfxp** [Y-Moshe/fxp-generator#28]
אנגלית => אנגלית ושפות זרות. לוגו חדש.
מדע ועובדות, חלל ואסטרונומיה אוחדו => מדע וחלל. לוגו חדש.
תודה.

**Comment by DanielNordman** [comment]
> אנגלית => אנגלית ושפות זרות. לוגו חדש. מדע ועובדות, חלל ואסטרונומיה אוחדו => מדע וחלל. לוגו חדש. תודה.

אפשר בבקשה את הקישורים הישירים ללוגואים של הפורומים?

**Comment by Webbfxp** [comment]
> > אנגלית => אנגלית ושפות זרות. לוגו חדש. מדע ועובדות, חלל ואסטרונומיה אוחדו => מדע וחלל. לוגו חדש. תודה.
> 
> אפשר בבקשה את הקישורים הישירים ללוגואים של הפורומים?

https://i.imagesup.co/images2/6e80a9866e0d2efe9c5d20db2894f89c06e45041.png אנגלית ושפות זרות
https://i.imagesup.co/images2/06594b95fa4204dbeb48e41c747c80ae54618bbf.png מדע וחלל
בבקשה

**Comment by DanielNordman** [comment]
@Y-Moshe תעדכן כאן בבקשה כשזה יעודכן.
שמות הפורומים שהיו לפני:
אנגלית
שפות ומדינות (הועבר לסל המחזור לפורומים)

ועכשיו שם הפורום המאוחד: אנגלית ושפות זרות
קישור ישיר לתמונה: https://i.imagesup.co/images2/6e80a9866e0d2efe9c5d20db2894f89c06e45041.png
קישור ישיר לאתגר השבוע: https://www.fxp.co.il/showthread.php?t=18749317

---

שמות הפורומים שהיו לפני:
חלל ואסטרונומיה
מדע ועובדות (הועבר לסל המחזור לפורומים)

ועכשיו שם הפורום המאוחד: מדע וחלל
קישור ישיר לתמונה: https://i.imagesup.co/images2/06594b95fa4204dbeb48e41c747c80ae54618bbf.png
קישור ישיר לאתגר השבוע: https://www.fxp.co.il/showthread.php?t=11421526
------------
בלי קשר התמונה לפורום פיקאופ ופיתוח עצמי עודכנה, נתתי לך את התמונה של הבאנר בטעות.
https://i.imagesup.co/images2/0df21d517d9a33a557f4dbbae60692941899a4b7.png

**Comment by Y-Moshe** [comment]
טופל.
