### ISSUE TITLE
בקשה לעדכון עיצוב במחולל משקיען ואשכול השבוע

### ISSUE THREAD

**Issue by Webbfxp** [Y-Moshe/fxp-generator#29]
אלה העיצובים החדשים-ישנים שאני מבקש להחליפם עם אלה שנוספו לפני זמן מה:

https://i.imagesup.co/images2/80043f099016ebfc34c801eb6ff9eac409dd9173.png

https://i.imagesup.co/images2/deeded2a2dc704989297e502b5fbc8310c4882f6.png

**Comment by DanielNordman** [comment]
השינוי הוצע, ברגע ש @Y-Moshe יבצע אותו הוא יעדכן כאן בעזרת ה'.

**Comment by Y-Moshe** [comment]
בוצע, תודה @DanielNordman
